import type { Metadata } from "next";
import { Heart, Leaf, Sparkles } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import { PageHero } from "@/components/page-hero";
import { getTeamWithWordPress } from "@/lib/wordpress";

export const metadata: Metadata = { title: "About", description: "Learn about Tupelo Honey Spa, a warm and inclusive spa and wellness collective in Elma, NY." };

export default async function AboutPage() {
  const team = await getTeamWithWordPress();
  return <><PageHero eyebrow="About Tupelo Honey" title="A softer place to land." copy="Beauty and wellness without the performance. This is expert care that makes room for you to show up exactly as you are." /><section className="section-pad"><div className="container-site grid gap-14 lg:grid-cols-2 lg:items-center"><div className="relative h-[600px] overflow-hidden rounded-[14rem_14rem_2rem_2rem] bg-[#d9c8b9]"><Image src={team[0].image} alt="Julie, founder of Tupelo Honey Spa" fill unoptimized className="object-cover object-top saturate-[.8]" /></div><div><span className="eyebrow">The story</span><h2 className="font-display mt-6 text-5xl leading-[.96] sm:text-6xl">Built around care,<br />not comparison.</h2><div className="mt-7 space-y-5 text-[.95rem] leading-8 text-[#676767]"><p>Tupelo Honey was created as a comfortable oasis where clients can step away from the world while receiving thoughtful, expert care.</p><p>What began with waxing and brows has grown into a true wellness collective: independent practitioners offering skincare, massage, Reiki, laser hair removal, makeup, and more—all under one welcoming roof.</p><p>The goal has never been to turn you into someone else. It is to support your confidence, help you feel at home in your body, and give you a reason to slow down.</p></div><Link href="/team" className="button-primary mt-8">Meet our collective</Link></div></div></section><section className="bg-[#ead6cf] py-20"><div className="container-site"><div className="grid gap-4 md:grid-cols-3">{[{ icon: Heart, title: "Every body is welcome", copy: "Care without judgment, pressure, or assumptions." }, { icon: Sparkles, title: "Expert over excessive", copy: "Honest recommendations from people who know their craft." }, { icon: Leaf, title: "Comfort counts", copy: "A warm environment designed to help you actually relax." }].map((value) => <div key={value.title} className="rounded-3xl border border-[#e4ded4] bg-[#f6f5e9]/70 p-8"><value.icon size={22} className="text-[#893d3e]" /><h3 className="font-display mt-8 text-3xl">{value.title}</h3><p className="mt-3 text-sm leading-7 text-[#676767]">{value.copy}</p></div>)}</div></div></section><section className="section-pad text-center"><div className="container-site"><h2 className="font-display text-5xl sm:text-7xl">Come as you are.</h2><p className="mx-auto mt-5 max-w-lg leading-7 text-[#676767]">We’ll take it from there.</p><Link href="/book" className="button-primary mt-8">Find an appointment</Link></div></section></>;
}
