"use client";

import { ArrowLeft, ArrowRight, CalendarDays, Check, CheckCircle2, ExternalLink, LoaderCircle, LockKeyhole, UserRound } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { categories, services, team } from "@/data/site";
import type { Availability } from "@/lib/booking/types";

type Props = { initialService?: string; initialProvider?: string };
const bookableTeam = team.filter((member) => !member.externalBooking);

export function BookingFlow({ initialService, initialProvider }: Props) {
  const validService = services.find((item) => item.slug === initialService)?.slug;
  const validProvider = bookableTeam.find((item) => item.slug === initialProvider)?.slug;
  const [step, setStep] = useState(validService ? 2 : 1);
  const [serviceSlug, setServiceSlug] = useState(validService ?? "");
  const [providerSlug, setProviderSlug] = useState(validProvider ?? "any");
  const [selectedTime, setSelectedTime] = useState("");
  const [availability, setAvailability] = useState<Availability[]>([]);
  const [loading, setLoading] = useState(false);
  const [complete, setComplete] = useState(false);
  const service = services.find((item) => item.slug === serviceSlug);
  const provider = team.find((item) => item.slug === providerSlug);

  useEffect(() => {
    if (step !== 3 || !serviceSlug) return;
    const controller = new AbortController();
    fetch(`/api/booking/availability?service=${serviceSlug}${providerSlug !== "any" ? `&provider=${providerSlug}` : ""}`, { signal: controller.signal })
      .then((response) => response.json()).then((data) => setAvailability(data.availability ?? [])).finally(() => setLoading(false));
    return () => controller.abort();
  }, [step, serviceSlug, providerSlug]);

  const grouped = useMemo(() => availability.reduce<Record<string, Availability[]>>((result, slot) => { const key = new Date(slot.startAt).toDateString(); result[key] = [...(result[key] ?? []), slot]; return result; }, {}), [availability]);
  function selectService(slug: string) { setServiceSlug(slug); setStep(2); window.scrollTo({ top: 0, behavior: "smooth" }); }
  function selectProvider(slug: string) { setProviderSlug(slug); setLoading(true); setStep(3); }
  function submitDetails(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setComplete(true); setStep(5); window.scrollTo({ top: 0, behavior: "smooth" }); }
  const progress = Math.min(step, 4);

  return <div className="container-site py-10 sm:py-16">
    <div className="mb-9 flex items-center justify-between gap-5"><div><span className="inline-flex rounded-full bg-[#ecd8be] px-3 py-1.5 text-[.62rem] font-bold uppercase tracking-[.13em] text-[#87412c]">Demo booking experience</span><h1 className="font-display mt-4 text-4xl sm:text-5xl">{complete ? "You’re all set." : "Book your visit"}</h1></div>{!complete && <span className="hidden text-xs text-[#807268] sm:block">Step {progress} of 4</span>}</div>
    {!complete && <div className="mb-10 grid grid-cols-4 gap-2" aria-label={`Step ${progress} of 4`}>{[1,2,3,4].map((item) => <div key={item} className={`h-1.5 rounded-full ${item <= progress ? "bg-[#a5482f]" : "bg-[#ded2c5]"}`} />)}</div>}
    <div className="grid gap-7 lg:grid-cols-[1fr_330px]">
      <div className="paper-card min-h-[560px] p-5 sm:p-8">
        {step === 1 && <div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#a5482f]">Choose a service</p><h2 className="font-display mt-2 text-3xl">What would feel good?</h2><div className="mt-7 space-y-8">{categories.map((category) => <section key={category}><h3 className="mb-3 text-xs font-bold text-[#685c52]">{category}</h3><div className="grid gap-2 sm:grid-cols-2">{services.filter((item) => item.category === category).map((item) => <button key={item.slug} onClick={() => selectService(item.slug)} className="flex min-h-20 items-center justify-between rounded-2xl border border-[#e3d7ca] bg-white p-4 text-left transition hover:border-[#b35b42] hover:bg-[#fffaf4]"><span><span className="block text-sm font-bold">{item.name}</span><span className="mt-1 block text-xs text-[#827369]">{item.price}{item.duration ? ` · ${item.duration}` : ""}</span></span><ArrowRight size={15} className="shrink-0 text-[#a5482f]" /></button>)}</div></section>)}</div></div>}
        {step === 2 && <div><button onClick={() => setStep(1)} className="mb-6 flex items-center gap-2 text-xs font-bold text-[#7a6b61]"><ArrowLeft size={14} /> Change service</button><p className="text-xs font-bold uppercase tracking-[.14em] text-[#a5482f]">Choose a specialist</p><h2 className="font-display mt-2 text-3xl">Who would you like to see?</h2><div className="mt-7 grid gap-3 sm:grid-cols-2"><button onClick={() => selectProvider("any")} className="flex min-h-28 items-center gap-4 rounded-2xl border border-[#dfd2c5] bg-white p-4 text-left hover:border-[#a5482f]"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-full bg-[#efe2d4] text-[#a5482f]"><CalendarDays size={20} /></span><span><span className="block text-sm font-bold">First available</span><span className="mt-1 block text-xs leading-5 text-[#827369]">Show the soonest opening with any qualified specialist.</span></span></button>{bookableTeam.map((member) => <button key={member.slug} onClick={() => selectProvider(member.slug)} className="flex min-h-28 items-center gap-4 rounded-2xl border border-[#dfd2c5] bg-white p-4 text-left hover:border-[#a5482f]"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-full bg-[#efe2d4] text-[#a5482f]"><UserRound size={20} /></span><span><span className="block text-sm font-bold">{member.name}</span><span className="mt-1 block text-xs text-[#827369]">{member.role}</span></span></button>)}<a href="https://book-a-massage-today.square.site/" target="_blank" rel="noreferrer" className="flex min-h-28 items-center gap-4 rounded-2xl border border-[#dfd2c5] bg-white p-4 text-left hover:border-[#a5482f]"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-full bg-[#efe2d4] text-[#a5482f]"><ExternalLink size={19} /></span><span><span className="block text-sm font-bold">Holli Simme</span><span className="mt-1 block text-xs leading-5 text-[#827369]">Continue to Holli’s secure Square booking site.</span></span></a></div></div>}
        {step === 3 && <div><button onClick={() => setStep(2)} className="mb-6 flex items-center gap-2 text-xs font-bold text-[#7a6b61]"><ArrowLeft size={14} /> Change specialist</button><p className="text-xs font-bold uppercase tracking-[.14em] text-[#a5482f]">Choose a time</p><h2 className="font-display mt-2 text-3xl">Find a time that works.</h2>{loading ? <div className="grid min-h-[360px] place-items-center"><LoaderCircle className="animate-spin text-[#a5482f]" /></div> : <div className="mt-7 space-y-7">{Object.entries(grouped).map(([day, slots]) => <section key={day}><h3 className="mb-3 text-sm font-bold">{new Date(day).toLocaleDateString("en-US", { weekday: "long", month: "long", day: "numeric" })}</h3><div className="flex flex-wrap gap-2">{slots.map((slot) => <button key={slot.startAt} onClick={() => setSelectedTime(slot.startAt)} className={`rounded-full border px-4 py-2.5 text-xs font-bold ${selectedTime === slot.startAt ? "border-[#a5482f] bg-[#a5482f] text-white" : "border-[#d9cbbd] bg-white hover:border-[#a5482f]"}`}>{slot.label}</button>)}</div></section>)}</div>}<button disabled={!selectedTime} onClick={() => setStep(4)} className="button-primary mt-8 w-full disabled:cursor-not-allowed disabled:opacity-40">Continue <ArrowRight size={15} /></button></div>}
        {step === 4 && <form onSubmit={submitDetails}><button type="button" onClick={() => setStep(3)} className="mb-6 flex items-center gap-2 text-xs font-bold text-[#7a6b61]"><ArrowLeft size={14} /> Change time</button><p className="text-xs font-bold uppercase tracking-[.14em] text-[#a5482f]">Your details</p><h2 className="font-display mt-2 text-3xl">Almost there.</h2><div className="mt-7 grid gap-4 sm:grid-cols-2"><Field label="First name" name="firstName" /><Field label="Last name" name="lastName" /><Field label="Email address" name="email" type="email" /><Field label="Mobile number" name="phone" type="tel" /></div><label className="mt-4 block text-xs font-bold text-[#62564d]">Anything we should know? <span className="font-normal text-[#95867a]">Optional</span><textarea name="note" rows={4} className="mt-2 w-full resize-none rounded-xl border border-[#d9cbbd] bg-white p-4 font-normal outline-none focus:border-[#a5482f]" /></label><label className="mt-5 flex items-start gap-3 text-xs leading-5 text-[#756a61]"><input required type="checkbox" className="mt-1 accent-[#a5482f]" />I understand this is a design preview and no live appointment will be created.</label><button className="button-primary mt-6 w-full" type="submit">Preview confirmation <ArrowRight size={15} /></button><p className="mt-4 flex items-center justify-center gap-1.5 text-[.68rem] text-[#8b7b70]"><LockKeyhole size={12} /> Square payment will be securely connected before launch.</p></form>}
        {step === 5 && <div className="grid min-h-[500px] place-items-center text-center"><div><span className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-[#dfe8d9] text-[#65705b]"><CheckCircle2 size={30} /></span><p className="mt-6 text-xs font-bold uppercase tracking-[.15em] text-[#78806a]">Demo complete</p><h2 className="font-display mt-3 text-4xl">This is how easy it will feel.</h2><p className="mx-auto mt-4 max-w-md text-sm leading-7 text-[#756a61]">No appointment was created. Once Square is connected, this screen will include a real confirmation number, calendar link, and management link.</p><button onClick={() => { setStep(1); setComplete(false); setServiceSlug(""); setSelectedTime(""); }} className="button-secondary mt-7">Start over</button></div></div>}
      </div>
      <aside className="h-fit rounded-3xl bg-[#302923] p-6 text-white lg:sticky lg:top-[110px]"><p className="text-[.65rem] font-bold uppercase tracking-[.14em] text-[#e3b66e]">Your visit</p>{service ? <><h2 className="font-display mt-4 text-3xl">{service.name}</h2><p className="mt-2 text-sm text-white/60">{service.category}</p><dl className="mt-6 space-y-4 border-t border-white/15 pt-5 text-xs"><div className="flex justify-between gap-4"><dt className="text-white/50">Price</dt><dd className="text-right font-bold">{service.price}</dd></div>{service.duration && <div className="flex justify-between gap-4"><dt className="text-white/50">Duration</dt><dd className="text-right font-bold">{service.duration}</dd></div>}<div className="flex justify-between gap-4"><dt className="text-white/50">Specialist</dt><dd className="text-right font-bold">{provider?.name ?? (providerSlug === "any" ? "First available" : "Not selected")}</dd></div>{selectedTime && <div className="flex justify-between gap-4"><dt className="text-white/50">Time</dt><dd className="text-right font-bold">{new Date(selectedTime).toLocaleString("en-US", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" })}</dd></div>}</dl></> : <p className="mt-4 text-sm leading-6 text-white/55">Choose a service to see your visit details here.</p>}<div className="mt-7 rounded-2xl bg-white/8 p-4"><p className="flex gap-2 text-xs font-bold"><Check size={14} className="text-[#e3b66e]" /> No payment today</p><p className="mt-2 text-[.68rem] leading-5 text-white/45">This preview uses mock availability and does not communicate with Square.</p></div></aside>
    </div>
  </div>;
}

function Field({ label, name, type = "text" }: { label: string; name: string; type?: string }) { return <label className="text-xs font-bold text-[#62564d]">{label}<input required name={name} type={type} className="mt-2 h-12 w-full rounded-xl border border-[#d9cbbd] bg-white px-4 font-normal outline-none focus:border-[#a5482f]" /></label>; }
