"use client";

import { ArrowRight, Clock, Search, X } from "lucide-react";
import Link from "next/link";
import { useMemo, useState } from "react";
import { categoryIntro, type Service } from "@/data/site";

export function ServiceExplorer({ initialCategory = "All", categories, services }: { initialCategory?: string; categories: string[]; services: Service[] }) {
  const safeInitialCategory = categories.includes(initialCategory) ? initialCategory : "All";
  const [category, setCategory] = useState(safeInitialCategory);
  const [query, setQuery] = useState("");
  const filtered = useMemo(() => services.filter((service) => (category === "All" || service.category === category) && `${service.name} ${service.description}`.toLowerCase().includes(query.toLowerCase())), [category, query, services]);
  return <div>
    <div className="sticky top-[84px] z-30 border-b border-[#e4ded4] bg-[#f6f5e9]/95 py-4 backdrop-blur-xl lg:top-[118px]"><div className="container-site flex flex-col gap-3 lg:flex-row lg:items-center"><div className="relative min-w-[230px] grow"><Search size={16} className="absolute left-4 top-1/2 -translate-y-1/2 text-[#676767]" /><input value={query} onChange={(event) => setQuery(event.target.value)} className="h-12 w-full rounded-full border border-[#d8cfc5] bg-white/70 pl-11 pr-10 text-sm outline-none focus:border-[#893d3e]" placeholder="Search treatments" aria-label="Search services" />{query && <button onClick={() => setQuery("")} aria-label="Clear search" className="absolute right-4 top-1/2 -translate-y-1/2"><X size={15} /></button>}</div><div className="flex gap-2 overflow-x-auto pb-1 lg:pb-0">{["All", ...categories].map((item) => <button key={item} onClick={() => setCategory(item)} className={`shrink-0 rounded-full border px-4 py-2.5 text-xs font-bold transition ${category === item ? "border-[#893d3e] bg-[#893d3e] text-white" : "border-[#d8cfc5] bg-transparent text-[#676767] hover:bg-white"}`}>{item}</button>)}</div></div></div>
    <div className="container-site py-14"><div className="mb-10"><p className="text-xs font-bold uppercase tracking-[.15em] text-[#893d3e]">{filtered.length} services</p><h2 className="font-display mt-2 text-4xl">{category === "All" ? "Everything we offer" : category}</h2>{category !== "All" && <p className="mt-3 max-w-2xl text-sm leading-7 text-[#676767]">{categoryIntro[category] ?? "Explore services currently available at Tupelo Honey."}</p>}</div>{filtered.length ? <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{filtered.map((service) => <article key={service.slug} className="paper-card group flex min-h-[260px] flex-col p-6 transition hover:-translate-y-1 hover:shadow-[0_18px_45px_#00032c0e]"><div className="flex items-start justify-between gap-5"><p className="text-[.65rem] font-bold uppercase tracking-[.14em] text-[#893d3e]">{service.category}</p><p className="shrink-0 text-sm font-bold">{service.price}</p></div><h3 className="font-display mt-4 text-3xl leading-none">{service.name}</h3><p className="mt-4 grow text-sm leading-6 text-[#676767]">{service.description}</p><div className="mt-7 flex items-center justify-between border-t border-[#e4ded4] pt-4">{service.duration ? <span className="flex items-center gap-1.5 text-xs text-[#676767]"><Clock size={14} />{service.duration}</span> : <span />}<Link href={`/book?service=${service.slug}`} className="flex items-center gap-1.5 text-xs font-bold text-[#893d3e]">Book <ArrowRight size={14} className="transition-transform group-hover:translate-x-1" /></Link></div></article>)}</div> : <div className="paper-card py-20 text-center"><p className="font-display text-3xl">No services found.</p><button onClick={() => { setCategory("All"); setQuery(""); }} className="button-secondary mt-5">Reset filters</button></div>}</div>
  </div>;
}
