"use client";

import { ArrowRight, Clock, Search, X } from "lucide-react";
import Link from "next/link";
import { useMemo, useState } from "react";
import { categories, categoryIntro, services } from "@/data/site";

export function ServiceExplorer() {
  const [category, setCategory] = useState("All");
  const [query, setQuery] = useState("");
  const filtered = useMemo(() => services.filter((service) => (category === "All" || service.category === category) && `${service.name} ${service.description}`.toLowerCase().includes(query.toLowerCase())), [category, query]);
  return <div>
    <div className="sticky top-[82px] z-30 border-b border-[#e8ddd0] bg-[#fbf6ee]/95 py-4 backdrop-blur-xl"><div className="container-site flex flex-col gap-3 lg:flex-row lg:items-center"><div className="relative min-w-[230px] grow"><Search size={16} className="absolute left-4 top-1/2 -translate-y-1/2 text-[#88786c]" /><input value={query} onChange={(event) => setQuery(event.target.value)} className="h-12 w-full rounded-full border border-[#d9cbbd] bg-white/70 pl-11 pr-10 text-sm outline-none focus:border-[#a5482f]" placeholder="Search treatments" aria-label="Search services" />{query && <button onClick={() => setQuery("")} aria-label="Clear search" className="absolute right-4 top-1/2 -translate-y-1/2"><X size={15} /></button>}</div><div className="flex gap-2 overflow-x-auto pb-1 lg:pb-0">{["All", ...categories].map((item) => <button key={item} onClick={() => setCategory(item)} className={`shrink-0 rounded-full border px-4 py-2.5 text-xs font-bold transition ${category === item ? "border-[#a5482f] bg-[#a5482f] text-white" : "border-[#d9cbbd] bg-transparent text-[#65594f] hover:bg-white"}`}>{item}</button>)}</div></div></div>
    <div className="container-site py-14"><div className="mb-10"><p className="text-xs font-bold uppercase tracking-[.15em] text-[#a5482f]">{filtered.length} services</p><h2 className="font-display mt-2 text-4xl">{category === "All" ? "Everything we offer" : category}</h2>{category !== "All" && <p className="mt-3 max-w-2xl text-sm leading-7 text-[#756a61]">{categoryIntro[category]}</p>}</div>{filtered.length ? <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{filtered.map((service) => <article key={service.slug} className="paper-card group flex min-h-[260px] flex-col p-6 transition hover:-translate-y-1 hover:shadow-[0_18px_45px_#4d35240e]"><div className="flex items-start justify-between gap-5"><p className="text-[.65rem] font-bold uppercase tracking-[.14em] text-[#a5482f]">{service.category}</p><p className="shrink-0 text-sm font-bold">{service.price}</p></div><h3 className="font-display mt-4 text-3xl leading-none">{service.name}</h3><p className="mt-4 grow text-sm leading-6 text-[#756a61]">{service.description}</p><div className="mt-7 flex items-center justify-between border-t border-[#e8ddd0] pt-4">{service.duration ? <span className="flex items-center gap-1.5 text-xs text-[#827268]"><Clock size={14} />{service.duration}</span> : <span />}<Link href={`/book?service=${service.slug}`} className="flex items-center gap-1.5 text-xs font-bold text-[#9d4029]">Book <ArrowRight size={14} className="transition-transform group-hover:translate-x-1" /></Link></div></article>)}</div> : <div className="paper-card py-20 text-center"><p className="font-display text-3xl">No services found.</p><button onClick={() => { setCategory("All"); setQuery(""); }} className="button-secondary mt-5">Reset filters</button></div>}</div>
  </div>;
}
